FROM python:3.12-slim

WORKDIR /app


RUN pip install --no-cache-dir streamlit==1.41.1 requests==2.32.3 python-dotenv==1.1.0


COPY frontend/ ./frontend/

EXPOSE 8501

CMD ["streamlit", "run", "frontend/app.py", "--server.address", "0.0.0.0"]
